import { readdirSync, statSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { generateKubernetesTypesFromSwagger } from './generate-k8s-resource-types';
import { generateOpenShiftTypesFromAPI } from './generate-openshift-crd-types';
import { toSafeString } from './utils/toSafeString';

const countTypeFiles = (dir: string): number => {
  let count = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      count += countTypeFiles(join(dir, entry.name));
    } else if (
      entry.isFile() &&
      entry.name.endsWith('.d.ts') &&
      entry.name !== 'index.d.ts' &&
      entry.name !== 'all.d.ts' &&
      entry.name !== 'latest.d.ts'
    ) {
      count++;
    }
  }
  return count;
};

const formatBytes = (bytes: number): string => {
  if (bytes < 1024) return `${bytes} B`;
  const kb = bytes / 1024;
  if (kb < 1024) return `${kb.toFixed(1)} KB`;
  return `${(kb / 1024).toFixed(1)} MB`;
};

const totalSize = (dir: string): number => {
  let size = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      size += totalSize(fullPath);
    } else if (entry.isFile()) {
      size += statSync(fullPath).size;
    }
  }
  return size;
};

const generateIndexFile = () => {
  writeFileSync(
    resolve(__dirname, '../dist/index.d.ts'),
    `// This file is autogenerated from the corresponding resources.
// Do not edit this file directly.

export * from './k8s-common';
export * from './kubernetes';
export * from './openshift';

`,
  );
};

const generateGVKIndexFiles = (platform: string) => {
  // recursively generate index files for group, version, and kind folders in dist/kubernetes and dist/openshift
  const basePath = resolve(__dirname, `../dist/${platform}`);

  const generateIndex = (dir: string) => {
    const items = readdirSync(dir, { withFileTypes: true });
    const indexLines: string[] = [
      `// This file is autogenerated from the corresponding resources.`,
      `// Do not edit this file directly.`,
      ``,
    ];

    items.forEach((item: any) => {
      if (item.isDirectory()) {
        const subDir = join(dir, item.name);
        generateIndex(subDir);

        // Use "as" to avoid export conflicts
        indexLines.push(`export * as ${toSafeString(item.name)} from './${item.name}';`);
      } else if (
        item.isFile() &&
        item.name.endsWith('.d.ts') &&
        item.name !== 'index.d.ts' &&
        item.name !== 'all.d.ts' &&
        item.name !== 'latest.d.ts'
      ) {
        const typeName = item.name.replace('.d.ts', '');

        // we know types are unique so we can just export them directly
        indexLines.push(`export { ${typeName}Kind } from './${typeName}';`);
      }
    });

    if (indexLines.length > 2) {
      writeFileSync(join(dir, 'index.d.ts'), indexLines.join('\n') + '\n');
    }
  };

  generateIndex(basePath);
};

const distDir = resolve(__dirname, '../dist');

generateIndexFile();
(async () => {
  await generateOpenShiftTypesFromAPI();
  generateGVKIndexFiles('openshift');
  await generateKubernetesTypesFromSwagger();
  generateGVKIndexFiles('kubernetes');

  const k8sDir = resolve(distDir, 'kubernetes');
  const osDir = resolve(distDir, 'openshift');
  const k8sCount = countTypeFiles(k8sDir);
  const osCount = countTypeFiles(osDir);

  console.log(`\nGenerated ${k8sCount + osCount} types (${formatBytes(totalSize(distDir))})`);
  console.log(`  Kubernetes: ${k8sCount}`);
  console.log(`  OpenShift:  ${osCount}`);
})();
