import path from 'path';
import { pluginSharedModules } from '@monorepo/sample-app/src/shared-modules';
import { DynamicRemotePlugin } from '@openshift/dynamic-plugin-sdk-webpack';
import type { Configuration as RspackConfiguration } from '@rspack/core';
import type { Configuration as WebpackConfiguration } from 'webpack';
import extensions from './plugin-extensions';
import pluginMetadata from './plugin-metadata';

const isProd = process.env.NODE_ENV === 'production';

const isRunningWebpack = !!process.env.WEBPACK;
const isRunningRspack = !!process.env.RSPACK;

if (!isRunningWebpack && !isRunningRspack) {
  throw new Error('Unknown bundler');
}

const pathTo = (relativePath: string) => path.resolve(__dirname, relativePath);

async function buildConfig(): Promise<WebpackConfiguration | RspackConfiguration> {
  const { EnvironmentPlugin, CSSMinimizerPlugin } = isRunningWebpack
    ? await Promise.all([import('webpack'), import('css-minimizer-webpack-plugin')]).then(
        ([webpack, cssMinimizer]) => ({
          EnvironmentPlugin: webpack.EnvironmentPlugin,
          CSSMinimizerPlugin: cssMinimizer.default,
        }),
      )
    : await import('@rspack/core').then((rspack) => ({
        EnvironmentPlugin: rspack.EnvironmentPlugin,
        CSSMinimizerPlugin: rspack.LightningCssMinimizerRspackPlugin,
      }));

  const plugins = [
    new EnvironmentPlugin({
      NODE_ENV: 'development',
    }),
    new DynamicRemotePlugin({
      pluginMetadata,
      extensions,
      sharedModules: pluginSharedModules,
      entryScriptFilename: isProd ? 'plugin-entry.[contenthash].min.js' : 'plugin-entry.js',
    }),
  ];

  return {
    mode: isProd ? 'production' : 'development',
    entry: {}, // Plugin container entry is generated by DynamicRemotePlugin
    output: {
      path: pathTo('dist'),
      publicPath: 'http://localhost:9001/',
      chunkFilename: isProd ? 'chunks/[id].[chunkhash].min.js' : 'chunks/[id].js',
      assetModuleFilename: isProd ? 'assets/[contenthash][ext]' : 'assets/[name][ext]',
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx'],
    },
    module: {
      rules: [
        {
          test: /\.(jsx?|tsx?)$/,
          exclude: /\/node_modules\//,
          use: [
            {
              loader: 'ts-loader',
              options: {
                configFile: pathTo('tsconfig.json'),
              },
            },
          ],
        },
        {
          test: /\.(svg|png|jpg|jpeg|gif)$/,
          include: pathTo('src'),
          type: 'asset',
          parser: {
            dataUrlCondition: {
              maxSize: 50 * 1024, // Files smaller than 50 kB will be inlined as data URLs
            },
          },
          generator: {
            filename: isProd ? 'images/[contenthash][ext]' : 'images/[name][ext]',
          },
        },
        {
          test: /\.(css)$/,
          include: pathTo('src'),
          use: ['style-loader', 'css-loader'],
        },
      ],
    },
    plugins,
    devtool: isProd ? 'source-map' : 'cheap-source-map',
    optimization: {
      minimize: isProd,
      minimizer: [
        '...', // The '...' string represents the webpack default TerserPlugin instance
        new CSSMinimizerPlugin(),
      ],
    },
  };
}

export default buildConfig();
