import path from 'path';
import { pluginSharedModules } from '@monorepo/sample-app/src/shared-modules';
import { DynamicRemotePlugin } from '@openshift/dynamic-plugin-sdk-webpack';
import CSSMinimizerPlugin from 'css-minimizer-webpack-plugin';
import type { Configuration, WebpackPluginInstance } from 'webpack';
import { EnvironmentPlugin } from 'webpack';
import extensions from './plugin-extensions';
import pluginMetadata from './plugin-metadata';

const isProd = process.env.NODE_ENV === 'production';

const pathTo = (relativePath: string) => path.resolve(__dirname, relativePath);

const plugins: WebpackPluginInstance[] = [
  new EnvironmentPlugin({
    NODE_ENV: 'development',
  }),
  new DynamicRemotePlugin({
    pluginMetadata,
    extensions,
    sharedModules: pluginSharedModules,
    entryScriptFilename: isProd ? 'plugin-entry.[contenthash].min.js' : 'plugin-entry.js',
  }),
];

const config: Configuration = {
  mode: isProd ? 'production' : 'development',
  entry: {}, // Plugin container entry is generated by DynamicRemotePlugin
  output: {
    path: pathTo('dist'),
    publicPath: 'http://localhost:9001/',
    chunkFilename: isProd ? 'chunks/[id].[chunkhash].min.js' : 'chunks/[id].js',
    assetModuleFilename: isProd ? 'assets/[contenthash][ext]' : 'assets/[name][ext]',
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
  },
  module: {
    rules: [
      {
        test: /\.(jsx?|tsx?)$/,
        exclude: /\/node_modules\//,
        use: [
          {
            loader: 'ts-loader',
            options: {
              configFile: pathTo('tsconfig.json'),
            },
          },
        ],
      },
      {
        test: /\.(svg|png|jpg|jpeg|gif)$/,
        include: pathTo('src'),
        type: 'asset',
        parser: {
          dataUrlCondition: {
            maxSize: 50 * 1024, // Files smaller than 50 kB will be inlined as data URLs
          },
        },
        generator: {
          filename: isProd ? 'images/[contenthash][ext]' : 'images/[name][ext]',
        },
      },
      {
        test: /\.(css)$/,
        include: pathTo('src'),
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
  plugins,
  devtool: isProd ? 'source-map' : 'cheap-source-map',
  optimization: {
    minimize: isProd,
    minimizer: [
      '...', // The '...' string represents the webpack default TerserPlugin instance
      new CSSMinimizerPlugin(),
    ],
  },
};

export default config;
